language: python

sudo: false

addons:
  apt:
    packages:
    - g++
    - gfortran
    - swig
    - python-qt4
    - libblas-dev
    - liblapack-dev
    - libatlas-dev

python:
- '2.7'

before_install:
- pip install --quiet --upgrade pip

install:
- pip install --quiet --upgrade numpy
- python setup.py develop

script: nosetests cytoflow

deploy:
  provider: pypi
  user: bteague
  password:
    secure: sM8peynamiTf+GWSnBoNcURHKTRzN6b/CMICrIwkZWcFNuCap1wj7vduRaGTasIpxNwMlPXvQkz7z7+Zkp5Xt82JYSIzU638l1MucNDKO36ttkuEE+Bj9+SASYmIoMxKjmxyGpVhlPDVS5hqIyEH7aR/nrNfCYlWt9LuAlNzEB4eZ38AyUiu5RItLxihMyq0olNM9IyF4Eo7KjI3+BzM0pp8Rx+huk8Hcsa6a/jAFhcf/0aFDGlBRsxy8GsNcn1e5RI1dQYqjoQ10AbFdSgFrFpurV306at6sEavNzL/lOvIOLV8SIo8+GZlbodgiNW7wCZ+nJhHzhW7V+rEBjNvdF40cMrRl26NwZYLmfPj/cijU3CsFLsSe0DpkVdEHF41fqtY9lTb8kwOiaLuYSELkRK/C2POTdyqkVzyoEZ5oMalPhWI+EmpdiAC+BfWx9TS1UeHaujWKD/xoMASR2hKEcncRlFRUj5gnYC9r7VKxJihLWpeQ3ZQhICxp4eWQijTTDwrnESlkhWv4U4yVksRoiU9AFrr1NNI1mygq70lFLTGA9Vud8Qq1MUl6U3cVPKnw8QhDTPdsRJ1qP8xWAYRblQPKEU6OGV3NtZP0JdKXt3Gzixe9HEXx5tfqbb2d5FPNsOWPNcL0oDuAzlD0tizY5I9pHS5QKBu0L8ekUALPj8=
  on:
    repo: bpteague/cytoflow
    branch: master
    tags: true
  server: https://pypi.python.org/pypi
  skip_cleanup: true
