language: python

sudo: false

addons:
  apt:
    packages:
    - g++
    - gfortran
    - swig
    - python-qt4
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    
python:
  - "2.7"
  
before_install:
  - pip install --quiet --upgrade pip

install:
  - echo "version `$CXX --version`"

  # i'm not quite clear on why this has to be installed directly, instead
  # of as a dependency of, say, pandas.  something to do with wanting you to
  # use a pre-packaged version, which is more likely to have a non-broken linear
  # algebra library?
  - pip install --quiet --upgrade numpy
#  - pip install --quiet --upgrade scipy
#  - pip install --quiet --upgrade pandas
#  - pip install --quiet --upgrade FlowCytometryTools
#  - pip install --quiet --upgrade seaborn
#  - pip install --quiet --upgrade pyface
#  - pip install --quiet --upgrade envisage
  
  - python setup.py develop

# command to run tests
script: nosetests

on_success:

  # TODO: upload the content of dist/*.whl to a public wheelhouse
  - pip install wheel
  - python setup.py bdist_wheel