language: python

sudo: false

addons:
  apt:
    packages:
    - g++
    - gfortran
    - swig
    - python-qt4
    - libblas-dev
    - liblapack-dev
    - libatlas-dev

python:
- '2.7'

before_install:
- pip install --quiet --upgrade pip

install:
- pip install --quiet --upgrade numpy
- python setup.py develop

script: nosetests cytoflow

deploy:
  provider: pypi
  user: Brian.Teague
  password:
    secure: "VmIEqabFmyfTFL3rI4Kx0N8DNcPqWo05adGGFR1D1ZO0Y36NODBWueyZ2lRZA/5GIW3dxDpwoQsNG6ZmnmbO76Shf+PAe6LoFmaVFPYV4azt+PlheTM6K7Ggsj/8RDE9Rn+yaodLFMPFlWYbhGnqiBIF+L2TcGfCR4uUP74BAIiHKI6ie+qW7sTdGIdKf6Ii3I0ph12mn42tcEabet6pAjVYwZ+GhpRjSrN1kv1wR/h3ROImaKUAXvWxLIZQM4+voYUV+tg0X5/Z3yCNgaHG+RbnPK+hLIiUQyG+IupnJ+i5yJKVW4JgOHt57EkpIsmgQ24Rc16PPg7CY1iUuReAt1kkDWMBEx6q8Kjv+nt8LEZuLCfgBD71/9vstWFlPvcPg0vKVOxTxWQfp2UFFOGmi1KQfu22UHE49GKKH8BBKisstxoyWEytlJ0z2hCu8ZSRQwXZ+P4zrQMKcidv52ftzMAYc0c68091FoZ/Ce1mrBpvDgSXx2uM1oGQKjYQZzRbrV+FLdF8R46yge1yibm2lw8VqFv/WDkvOpY5DoQW1QOU1SdS/T7ln3K8PNChQPkP6gp5gJ7SrJYMZfrB2QEXucDmv1Ma4X5Dl/LyTm/yeE+YQerCyYFBFRgx3xOyrgcRgX8f1u57jFCSGOhaJ6DCdJugySPjEEceCADBwUV2STA="
  on:
    repo: bpteague/cytoflow
    branch: master
    tags: true
  server: https://pypi.python.org/pypi
  skip_cleanup: true
