language: generic

env:
  global:
    - MPLBACKEND=Agg
    - secure: "vf7vH79kKrYrTlPQZfQLTBefBlPVllj+JnaWMTa38lza4hun5eY4wkJp2a1etOTHGQ52BgrR2dKKfQaMW88dwvKDtg0Fkjllud50A1MnswZyEXHEJDILOXpzcg/D52ZCp+FJ1CDzHUNCxIv/etfveb5pAVlAhewjqiATo1uUd87OP1HyxbGnZZK3p5kH+UIHDLWVzq8Cmavp8jLIYfzXkXrLfxEUloi9E0DtVQuew7DcchIK4QgXZ8SfRD5pCVutwhj/nwBh5SQQEshBh+sWeZfyi1/qlW25lS4Yeu3vpMcCf5z2pSJXb8/OMlTwoBhm8qfb9qk96wNyFIQ4zYebuONKxqZczYMdUisNQYbPZkUOO9ulixujyG50BVrs6mrRecEYdYqC1l8B5vpAAbZyxrU0GL5ebXrxsi1sSOwVi4m09v53nVsM8Cdu9tdjvIgVKNs5R4j8mFXMX+S7d+nDXWeE7mPsDOcLZMBRy+KG6UAUDJsZF+MUnvnE4Y1iXEPC3lNQ+cpeReWrGaeih8D54FJwfMX+HBlW9dz6/ArG5qS3x0UbtXJlmoHSegjFZcv6SKOn9TnF0UC2NryjvwECQDFFh+UesVxFwYD8i5Hpz6taIA8beY+Qiqf7FDK9UOp5Cd2pR013Har9Pb845nfsMGImXuVNes48UV9T/WGXpLM="    
    
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
      
    - os: osx
      osx_image: xcode6.4

addons:
  apt:
    sources:
      - sourceline: 'deb http://mirrors.mit.edu/ubuntu/ trusty-backports main restricted universe multiverse'
    packages:
      - g++
      - gfortran
      - swig3.0
      - python3-pyqt4
      - libblas-dev
      - liblapack-dev
      - libatlas-dev

before_install:

  # make sure distutils can find swig
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s `which swig3.0` ./swig; export PATH=`pwd`:$PATH; fi

  # setup anaconda 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig@3.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/swig@3.04/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi

  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Users/travis/miniconda3/bin:$PATH; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export PATH=/home/travis/miniconda3/bin:$PATH; export LD_LIBRARY_PATH=/home/travis/miniconda3/envs/py35/lib; fi
  - conda update --yes conda
  - conda config --add channels bpteague
  - conda install --yes --quiet anaconda-client conda-build
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3; fi

install:

  - conda build packaging/conda_recipes/cytoflow
  - conda create --yes --quiet --name=cytoflow python=3.5.4 nomkl
  - source activate cytoflow
  - conda install --yes --quiet --use-local cytoflow

before_script:
  - conda install --yes --quiet pip mock 
  - pip install nose2 

script: nose2 -c packaging/nose2.cfg -s cytoflow/tests -N 2

after_success:

  - pip install "sphinx==1.6.7"
  - pip install "pyinstaller==3.3.1"
  - python setup.py build_sphinx -b embedded_help

  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then python setup.py sdist; fi
  - python setup.py bdist_wheel

  - pyinstaller --log-level=DEBUG packaging/pyinstaller.spec
  - pyi-archive_viewer -l dist/cytoflow
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd dist/; zip -r cytoflow.macos.zip Cytoflow.app/; rm -rf Cytoflow.app cytoflow; cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then mv dist/cytoflow dist/cytoflow-linux.x86_64; fi
  - ls -al dist/*


deploy:
  - provider: releases
    api_key: 
      secure: "EiLTgjYPi2qgQWhxZzljvi8rLpJg7Seu6LQXAxqeQFCthkonsyzr+Wg44jLQfVKo5Y4KjiPN/QXbpmfvjT2wlTE1qhEwu8q9hDWhXtaHoQ8nDMEABVosvNWbCZc5xT8qSydglmtK2gkUfW7wICkgFEw7Tp7eOXN0XQOMph5LXDdnR0vrk7qR9TU3Ld3pbbCEliA02SZi0a2Es9+S72dwIJhjkhNlrVc0mqwZ5q3SAFGD+Txol/ZydWijN2iuvhDGzemOCAPi+3lyZvc7kcUSkdTNWjO8pwVn7MiYx+JDMsKxEL0yHLX0425TJMT+ptpNio6k+xk1Zmn2PmHLyWC+JcBfXG0qnvOjaVQ61hssSgb+ku3oDxO5UJpEmPOOP6A/f6x+PZPo9nm4s+2vU6dHH4YU/5CjZPF0/GuNBTYL5jJengATNVq2TQ368FPu+lUuYkUyrH2+jFLTprvE7iaEJAebb7KMiz5wBqn12uoybhKshV8v6PjXXHjDlIu7iDEnhZlY9pdhmFCNEmMLkvjzaUGjLBPG/WbeIiUuDyEt9xk7qP99fij8olJYxCDTa7JglZXytNj/VSo2BR+kY/cPPJimR4VX+U/82UVs/D3i3vmBf3/yf/vhRXGkozo616Vt2O8TS3xpj6LUNdOydiOPfIj+zAAu1NYeedZjkKpiy1M="
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on: 
      branch: master
      tags: true
      
  - provider: bintray
    file: packaging/bintray.json
    user: bpteague
    key:
      secure: "d88Bpab7ZSa4v7/RRtnADZKWqjRFc17S5/F1tTyyxqsFkuDfohc7KjLv5xcBZn/4dL0G00G47eFUY0caZ3pydKBtgoKZ8MymxioNjpKd2PiPHOcY04MGQJ1lApB/VqjKuZIruHdt+3TDTcgtJYhyTmaVkVy77YXM1ep6P4EHT/Ns/n0qZgsK6h4orRX9mY9FFYHRlnp/Mt2iJN7PCng/2DaOQ0F6yMXI3/RYHlfAPPKPBYL1eTmrvBuVViNDCGDkd19A6eWZnkT1SWF1KGa6BN9fW3pcNfL0PPBY43S2fekZmHstcbBsskzqG+VhIcfPNdB1RRZteBRwuzBpf+NylbCC8y01PbwZ4gGDVuho+2sqdWteV741XX25HqhV8WiET9c4rzbMvIAFb5qDDlZBzwikg/Dhlqu1ik+yiAeYEuq7NvCpGD4IMdVMR7B457Qe/7NvrAD8R9TCvWaHAxA9zTUlTL7lV0UGJDrdtbfpZsDMP8/uJh5a4CWjxvc4+h158NOLO6aRCqb/NRjeyhBlUdUJ1JWXb7Z9/mDZHKvZOvl+fzk0O7pGDFG6kKwXcq3VZmitFP6n3ZgE1Q3/TcF08N9JNqKkwXvAg/wlNlABucMi84bMyk9c6CI9MSXdM57Anf70zGCbNOClGsPbgWIHnZEwAIgR5xiIC6xS+oEsELo="
    dry-run: false
    skip_cleanup: true
    on:
      branch: packaging
      
  - provider: bintray
    file: packaging/bintray.json
    user: bpteague
    key:
      secure: "d88Bpab7ZSa4v7/RRtnADZKWqjRFc17S5/F1tTyyxqsFkuDfohc7KjLv5xcBZn/4dL0G00G47eFUY0caZ3pydKBtgoKZ8MymxioNjpKd2PiPHOcY04MGQJ1lApB/VqjKuZIruHdt+3TDTcgtJYhyTmaVkVy77YXM1ep6P4EHT/Ns/n0qZgsK6h4orRX9mY9FFYHRlnp/Mt2iJN7PCng/2DaOQ0F6yMXI3/RYHlfAPPKPBYL1eTmrvBuVViNDCGDkd19A6eWZnkT1SWF1KGa6BN9fW3pcNfL0PPBY43S2fekZmHstcbBsskzqG+VhIcfPNdB1RRZteBRwuzBpf+NylbCC8y01PbwZ4gGDVuho+2sqdWteV741XX25HqhV8WiET9c4rzbMvIAFb5qDDlZBzwikg/Dhlqu1ik+yiAeYEuq7NvCpGD4IMdVMR7B457Qe/7NvrAD8R9TCvWaHAxA9zTUlTL7lV0UGJDrdtbfpZsDMP8/uJh5a4CWjxvc4+h158NOLO6aRCqb/NRjeyhBlUdUJ1JWXb7Z9/mDZHKvZOvl+fzk0O7pGDFG6kKwXcq3VZmitFP6n3ZgE1Q3/TcF08N9JNqKkwXvAg/wlNlABucMi84bMyk9c6CI9MSXdM57Anf70zGCbNOClGsPbgWIHnZEwAIgR5xiIC6xS+oEsELo="
    dry-run: false
    skip_cleanup: true
    on:
      branch: master

  - provider: pypi
    user: Brian.Teague
    password:
      secure: P2kebBOVixLdfWV0UYKPa8Y87YIqWc4I1TAr6myTiTL1OGdHvAsoBL3hxP+84F8ZL52hnqUWL/GuRO+IIf4R4IJbIF8Nj8DQG28dN/jBNK/EgBd0ut6myv4yFht5aL5o7qsCpTZxxwDori0+7y8wkvAd/Dz5T+UNb5TzOT2W/aYBz2LRwJaJ2lmGPktCJfopVUxGD9iWCJV1imaw9IqBZof8v1bbkFGf06Lpgb8TKeGZGikiFiiDhDjXuVmsH8FysJV5KmiWUxNOvzZ6xNU+gqOLkVP3bZwM764ZKlU5GEkKP4Yfdru/ixicwm2bAENSQ4B9OZKnhrx8oycJLyrIMlEctWByva8Yj+zBvxPsSjwc+DvIjmbfJVnhAY0aWpMVfbfASlTny+dMjPesuGb/kieSD7rF4S82Zfs4mcNXF25QFteyjcTswp/WSdZMg7jmU23fi8XVMZxNHeYuZFciJW4DSpMM8nSWUXb5tT9NPUQmRKLGYGY4mFh+F2P6/exZwISzWkDIVZNAmOhGec8D00YmceVHe1dk4nX+i6BWojsP6KGmbAgIrZxmDJ8T/mWVWu0yAnU2QpyJMsbrPIaM7otNQaVoHwSk4c5IFcON2ZEdz/gs6KRd99M+fQBJzOEYS8WqNlOS+TpQhkmOhyU4xFuKv4ieyWLXu7PofQR9nAQ=
    on:
      repo: bpteague/cytoflow
      tags: true
    server: https://pypi.python.org/pypi
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    
  - provider: script
    script: ./packaging/deploy_anaconda.sh
    skip_cleanup: true
    on:
      branch: packaging
