environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\packaging\\appveyor\\run_with_compiler.cmd"

  matrix:

    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - ps: Update-AppveyorBuild -Version "$($env:appveyor_repo_commit.substring(0,7))"

install:
  - ECHO "Filesystem root:"
  - ps: "ls \"C:/\""

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  # - "powershell ./appveyor/install.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  
  # install swig
  - choco install swig -y

  # Install the build and runtime dependencies of the project.
  - conda install --yes --quiet numpy numexpr scipy matplotlib nose dateutil pandas statsmodels scikit-learn seaborn pyface=4.4.0 envisage pip
  - pip.exe install pyinstaller

  - "%WITH_COMPILER% python setup.py develop"

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py nosetests"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel bdist_wininst"
  - "pyinstaller.exe packaging/pyinstaller.spec"

artifacts:
  - path: dist\*
  - path: build\lib.win32-2.7\cytoflow\utility\logicle_ext\_Logicle.pyd
  - path: build\lib.win-amd64-2.7\cytoflow\utility\logicle_ext\_Logicle.pyd

deploy:
- provider: BinTray
  username: bpteague
  api_key:
    secure: BLgrF3vno40XZMvXZ+DGzxeO8xzQJP1Y/ndUVPEycNlNB2puWDGdPDJ8d4DxDTEj
  subject: bpteague
  repo: cytoflow
  package: cytoflow-dev
  #version: use the build version
  publish: false
  override: true
  
