name: cytoflow
channels:
 - bpteague
 
dependencies:
    - python==3.6.10
    - numpy==1.19.1
    - pandas==1.1.2
    - matplotlib==3.3.1
    - bottleneck==1.3.2
    - numexpr==2.7.1
    - scipy==1.5.0
    - scikit-learn==0.23.2
    - seaborn==0.11.0
    - statsmodels==0.11.1

    - traits==6.1.1
    - traitsui==7.0.1
    - pyface==7.0.1
    - envisage==4.9.2
    - nbformat==5.0.7
    - python-dateutil==2.8.1

    - pyqt==5.9.2
    - qt==5.9.7
    - pyopengl==3.1.1a1

    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0

    - mock==4.0.1
    - sphinx==3.2.1
    
    - notebook
