name: cytoflow
channels:
 - bpteague
 
dependencies:
    - python==3.6.7
    - numpy==1.15.4
    - pandas==0.23.4
    - bottleneck==1.2.1
    - numexpr==2.6.8
    - matplotlib==3.0.2
    - scipy==1.1.0
    - scikit-learn==0.20.1
    - traits==4.6.0
    - traitsui==6.0.0
    - pyface==6.0.0
    - envisage==4.7.0
    - nbformat==4.4.0
    - python-dateutil==2.7.5
    - statsmodels==0.9.0
    - pyqt==5.9.2
    - qt==5.9.7
    - fcsparser==0.2.0
    - camel==0.1.2
    - yapf==0.22.0
    - seaborn==0.9.0
    - pyopengl==3.1.1a1

    - mock==2.0.0
    - sphinx==1.8.2
    
    - notebook
