name: Test and package on MacOS
on: [push]
jobs:
      
  test-on-macos:
    name: Run nose2 on MacOS runner
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
        
    - name: Install SWIG
      run: |
        brew install swig@3
        echo "/usr/local/opt/swig@3/bin" >> $GITHUB_PATH
    
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Install nose2
      run: |
        pip install nose2
        
    - name: Run cytoflow tests
      env:
        OMP_NUM_THREADS: 1
      run: |
        nose2 -v -c package/nose2.cfg -s cytoflow/tests

#    - name: Run cytoflowgui tests
#      env:
#        OMP_NUM_THREADS: 1
#      run: |
#        source activate cytoflow
#        nose2 -v -c package/nose2.cfg -s cytoflowgui/tests -GUI        

    
  build-macos-conda-package:
    name: Build MacOS conda package
    runs-on: macos-10.15
    needs: test-on-macos
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
        
    - name: Install SWIG
      run: |
        brew install swig@3
        echo "/usr/local/opt/swig@3/bin" >> $GITHUB_PATH
                
    - name: Configure conda
      run: |
        conda install --name base --yes --quiet anaconda-client conda-build
        
    - name: Build conda package
      run: |
        conda deactivate
        conda render package/conda_recipes/cytoflow
        conda build package/conda_recipes/cytoflow
        
    - name: Move conda package into the dist folder
      run: |
        mkdir dist
        conda deactivate
        conda activate base
        python package/move_conda_package.py
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-conda-package
        retention-days: 1
        path: dist/*

  build-macos-wheels:
    name: Build MacOS wheels
    needs: test-on-macos
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
        
    - name: Install SWIG
      run: |
        brew install swig@3
        echo "/usr/local/opt/swig@3/bin" >> $GITHUB_PATH
            
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
        
    - name: Move C++ extensions into the dist folder
      run: |
        cp `find build | grep "\.so$"` dist/
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-wheels
        retention-days: 1
        path: dist/*   
        
  build-macos-oneclick:
    name: Build macos one-click
    needs: test-on-macos
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0
        
    - name: Query git tag
      id: tag
      uses: jimschubert/query-tag-action@v2
      with:
        skip-unshallow: true
        abbrev: false
        
    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tag.outputs.tag}}'
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
        
    - name: Install SWIG
      run: |
        brew install swig@3
        echo "/usr/local/opt/swig@3/bin" >> $GITHUB_PATH
            
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Install packaging deps
      run: |
        conda install --name cytoflow --yes --quiet 'sphinx==3.4.3'
        pip install "pyinstaller==4.1"
        
    - name: Build embedded help docs
      run: |
        python setup.py build_sphinx -b embedded_help
        
    - name: Build GUI binary
      run: |
        pyinstaller package/pyinstaller.spec
        
    - name: Rename and zip Mac app
      run: |
        cd dist/
        mv Cytoflow.app Cytoflow-${{steps.tag.outputs.tag}}.app
        zip -r cytoflow-${{steps.tag.outputs.tag}}.macos.zip 
        Cytoflow-${{steps.tag.outputs.tag}}.app/
        rm -rf Cytoflow-${{steps.tag.outputs.tag}}.app cytoflow
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-oneclick
        retention-days: 1
        path: dist/*
